spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 300MB
      max-request-size: 300MB
logging:
  level:
    org.springframework.security: TRACE
    org.zesta.app.librarymis: TRACE
file:
  upload:
    dir : upload
cloudinary:
  api_key: 177818943471628
  cloud_name: versusbet
  api_secret: inFBqAhZJdPCnDSzk6af9ixfP70