spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org.springframework.security: TRACE
    org.zesta.app.librarymis: TRACE